name: Django Test Post model

on:
  push:
    branches: ['main']

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.10.12]

    steps:
      - uses: actions/checkout@v3

      - name: Check Python version Before Install
        run: python3 --version

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Check Python version After Install
        run: python3 --version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Database Migrate
        run: |
          python manage.py makemigrations
          python manage.py migrate
          
      - name: Run The Tests
        run: |
          python manage.py test

